src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date d'arrivée doit être au bon format !")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être supérieure à celle d'aujourd'hui !", groups={"back"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date de départ doit être au bon format !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être supérieure à celle d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(max=8000, maxMessage="Le commentaire ne peut dépasser {{limit}} caractères !")
     */
    private $comments;

    /**
     * Callback appelé à chaque fois qu'on créé une réservation
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if(empty($this->createdAt))
        {
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount))
        {
            // Prix de l'annonce * le nombre de jours
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * Nombre de jours entre la date d'arrivée et celle de départ
     *
     */
    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    /**
     * Permet de connaître les dates disponibles
     */
    public function isBookableDates()
    {
        // Les dates indisponibles pour l'annonce
        $unavailableDays = $this->ad->getUnavailableDays();
        // Comparer les dates choisies avec les dates indisponibles
        $bookingDays = $this->getDays();

        // Tableau de chaines de caractères de mes journées
        $days = array_map(function($day)
        {
            return $day->format('Y-m-d');
        }, $bookingDays);

        $unavailableDay = array_map(function($day)
        {
            return $day->format('Y-m-d');
        }, $unavailableDays);

        foreach($days as $day)
        {
            if(array_search($day, $unavailableDay) !== false)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
    }

    /**
     * Permet de récupèrer le tableau  d'objets DateTime des jours de ma réservation
     */
    public function getDays()
    {
        $resultat = range
        (
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24*60*60
        );

        $days = array_map(function($dayTimestamp)
        {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Email déja utilisée !")
 * @UniqueEntity(fields={"pseudo"}, message="Pseudo déja utilisé !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Email(message="Veuillez saisir une adresse email valide !")
     * @Assert\Length(max=255, maxMessage="Votre email ne peut dépasser {{limit}} caractères !")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=4096, maxMessage="Votre mot de passe ne peut dépasser {{limit}} caractères !")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=255, maxMessage="Votre prénom ne peut dépasser {{limit}} caractères !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=255, maxMessage="Votre nom ne peut dépasser {{limit}} caractères !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=255, maxMessage="Votre pseudo ne peut dépasser {{limit}} caractères !")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Url(message="Veuillez saisir une url valide !")
     * @Assert\Length(max=255, maxMessage="Votre url ne peut dépasser {{limit}} caractères !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=255, maxMessage="Votre introduction ne peut dépasser {{limit}} caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=8000, maxMessage="Votre introduction ne peut dépasser {{limit}} caractères !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initilaliser le slug
     * Ici on définit le slug uniquement pour les nouvelles annonces
     * Les anciennes annonces, même mises à jour, garderont leur ancien slug,
     * pour garder un bon référencement(sur goolge par exemple)
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName." ".$this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName()
    {
        return $this->firstName. " " .$this->lastName;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="create_booking")
     * @Security("is_granted('ROLE_USER')")
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();

        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $user = $this->getUser();

            $booking->setBooker($user)
                    ->setAd($ad);
            
            // Si les dates ne sont pas disponibles, messsage d'erreur
            if(!$booking->isBookableDates())
            {
                $this->addFlash('warning', "Dates choisies non disponibles !");
            }
            else
            {
                $manager->persist($booking);
                $manager->flush();

                $this->addFlash('success', "Votre réservation a bien été prise en compte !");

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId()]);
            }
        }
        
        return $this->render('booking/book.html.twig', 
        [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher une réservation
     * 
     * @Route("/booking/{id}", name="booking_show")
     * 
     * @Security("is_granted('ROLE_USER') and user === booking.getBooker()", statusCode=403)
     *
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());
            
            $manager->persist($comment);
            $manager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été pris en compte !');
        }

        return $this->render("booking/show.html.twig", 
        [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation d'annonce{% endblock title %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
{% endblock stylesheets %}

{% block body %}
    <div class="container">
        <h4>Réserver pour l'annonce : <em>{{ad.title}}</em></h4>

        <p>Vous êtes sur le point de réserver l'annonce de <strong>{{ad.author.fullName}}</strong>, 
        veuillez renseigner votre date d'arrivée puis votre date de départ.</p>
    

        {{form_start(form)}}
            <div class="alert alert-light">
                <div class="row">
                    <div class="col-md-6">
                        {{form_row(form.startDate)}}
                    </div>
                    <div class="col-md-6">
                        {{form_row(form.endDate)}}
                    </div>
                </div>
                <h6 class="mt-3">Montant du séjour : <span id="amount">...</span>&euro;</h6>
                <span id="days">0</span> nuit(s) à {{ad.price|number_format('2', ',', ' ')}} &euro; par nuit.
                <h6 class="mt-3">Vous avez un commentaire ou message ?</h6>
                {{form_row(form.comments)}}
            </div>


            <button type="submit" class="btn btn-success">Je réserve !</button>

        {{form_end(form)}}
    </div>

{% endblock body %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js">
    </script>

    <script>
        $(function(){
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: 
                [
                    {% for day in ad.unavailableDays %}
                        "{{day.format('d/m/Y')}}",
                    {% endfor %}
                ],
                startDate: new Date()
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount()
        {
            // On chope les dates puis on les covertit dans un format général (18/09/2015 => 2015-09-18)
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if(startDate && endDate && startDate < endDate)
            {
                // La fonction getTime() renvoie le timestamp en millisecondes
                const interval = endDate.getTime() - startDate.getTime();
                const DAY_TIME = 24*60*60*1000;
                const days = interval / DAY_TIME;
                const amount = days * {{ad.price}};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock javascripts %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Réservation n°{{booking.id}}{% endblock title %}

{% block body %}
    <div class="container">
        <h2 class="my-4">Votre réservation (n°{{booking.id}})</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="alert alert-light">
                    <h4>Détails</h4>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate|date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate|date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombres de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount|number_format(2, ',', ' ')}} &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comments|default('Aucun commentaire')}}</dd>
                    </dl>
                    <hr>
                    <h4 class="alert-heading">Votre Hôte</h4>
                    <div class="row mb-3">
                        <div class="col-md-3">
                            <img src="{{booking.ad.author.picture}}" alt="{{booking.ad.author.fullName}}" 
                            class="avatar avatar-medium">
                        </div>
                        <div class="col-md-9">
                            <h6>
                                <a href="{{path('user_show', {'pseudo': booking.ad.author.pseudo})}}" >
                                {{booking.ad.author.fullName}}</a>
                            </h6>
                            <span class="badge badge-primary">{{booking.ad.author.ads|length}}
                            annonces</span>
                        </div>
                    </div>
                    {{booking.ad.author.introduction|raw}}
                </div>

                <div class="alert alert-light">
                    <h4 class="alert-heading">Votre avis compte !</h4>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <p>Le {{comment.createdAt|date('d/m/Y H:i')}} :</p>
                            <blockquote>{{comment.content}}</blockquote>

                            <strong>
                                Note : {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                            </strong>
                        {% else %}
                            {{ form_start(form)}}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-success">Valider</button>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        Vous pourrez laisser ici un avis sur votre réservation à la fin de votre séjour.
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-light">
                    <h4 class="alert-heading">Votre hébergement</h4>
                    <h6>
                        <a href="{{path('ads_show', {'slug': booking.ad.slug})}}">
                        {{booking.ad.title}}</a>
                    </h6>
                    <img src="{{booking.ad.coverImage}}" alt="Image de {{booking.ad.title}}" 
                    class="img-fluid my-3">
                    {{booking.ad.introduction|raw}}
                </div>
            </div>
        
        </div>
    </div>
{% endblock body %}