src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("title", message="Une annonce posséde déjà ce titre, merci de le modifier")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=255, maxMessage="Le titre ne peut dépasser {{limit}} caractères !")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\LessThan(value=1000000000, message = "Le prix ne peut dépasser {{ compared_value }}")
     * @Assert\GreaterThan(value=0, message = "Le prix doit être supérieur à {{ compared_value }}") 
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=8000, maxMessage="L'introduction ne peut dépasser {{limit}} caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Length(max=8000, maxMessage="Le contenu ne peut dépasser {{limit}} caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\Url(message="Veuillez saisir une url valide !")
     * @Assert\Length(max=255, maxMessage="L'url de l'image ne peut dépasser {{limit}} caractères !")
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Veuillez renseigner ce champ.")
     * @Assert\LessThan(value=1000, message = "Le nombre de chambres ne peut dépasser {{ compared_value }}")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initilaliser le slug
     * Ici on définit le slug uniquement pour les nouvelles annonces
     * Les anciennes annonces, même mises à jour, garderont leur ancien slug,
     * pour garder un bon référencement(sur goolge par exemple)
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de retourner le commentaire d'un auteur
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->comments as $comment)
        {
            if($comment->getAuthor() === $author)
            {
                return $comment;
            }
            else
            {
                null;
            }
        }
    }
    /**
     * Calcul la moyenne des notes d'une annonce
     *
     * @return moyenne
     */
    public function getAvgRatings()
    {
        // Calculer le somme des notes
        $sum = array_reduce($this->comments->toArray(), function($total, $comment)
        {
            $total += $comment->getRating();
            return $total;
        }, 0);

        // Faire la division pour avoir la moyenne
        if(count($this->comments) > 0)
        {
            return $sum / count($this->comments);
        }
        else
        {
            return 0;
        }
    }

    /**
     * Retourne un tableau d'objets Datetime représentant les jours indisponibles
     */
    public function getUnavailableDays()
    {
        $unavailableDays = [];

        foreach($this->bookings as $booking)
        {
            // Calculer les jours qui se trouvent entre la date d'arrivée et de celle de départ
            $resultat = range
            (
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24*60*60
            );

            $days = array_map(function($dayTimestamp)
            {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $unavailableDays = array_merge($unavailableDays, $days);
        }

        return $unavailableDays;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) 
        {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) 
        {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) 
            {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\User;
use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\RedirectResponse;



class AdController extends AbstractController
{
    /**
     * Liste toutes les annonces de la base de données
     * 
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();
        
        return $this->render('ad/index.html.twig', ['ads' => $ads]);
    }

    /**
     * Permet de créer une annonce
     * 
     * @Route("/ads/new", name="ads_create")
     * @Security("is_granted('ROLE_USER')")
     *
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager)
    {
        $ad = new Ad();

        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $ad->setAuthor($this->getUser());
            
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash('success' , 
                    'L\'annonce <strong>' . $ad->getTitle() . '</<strong> a bien été enregistrée !');

           return $this->redirectToRoute('ads_show', ['slug' => $ad->getSlug()]);
        }
        
        return $this->render("ad/new.html.twig", ['form' => $form->createView()]);
    }

    /**
     * Permet d'afficher le formulaire d'édition
     * 
     * @Route("ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous ne pouvez modifier cette annonce !")
     * 
     * @return Response
     */
    public function edit(Ad $ad, Request $request, ObjectManager $manager)
    {
        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash('success' , 
                    'Les modifications de l\'annonce <strong>' . $ad->getTitle() . 
                    '</strong> ont bien été enregistrées !');

           return $this->redirectToRoute('ads_show', ['slug' => $ad->getSlug()]);
        }
        
        return $this->render('ad/edit.html.twig', ['form' => $form->createView(), 'ad' => $ad]);
    }

    /**
     * Permet de supprimer une annonce
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous ne pouvez supprimer cette annonce !")
     *
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     */
    public function delete(Ad $ad, ObjectManager $manager)
    {
        $user = $this->getUser();

        $manager->remove($ad);
        $manager->flush();

        $this->addFlash('success', "L'annonce : <strong>".$ad->getTitle()."</strong> a bien été supprimée");

        return $this->redirectToRoute("user_show", ['pseudo' => $user->getPseudo()]);
    }

    /**
     * Permet d'afficher une seule annonce
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad)
    {
        $user = $ad->getAuthor();

        return $this->render("ad/show.html.twig", ['ad' => $ad, 'user' => $user]);
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug' : ad.slug}) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strontg>{{ ad.price|number_format(2, ',', ' ') }} &euro; / nuit</strong> <br>

            {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>

        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement"
            style="height: 200px; width: 100%; display: block">
        </a>

        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ url }}">{{ ad.title }}</a>
            </h4>
            <p class="card-text">
                {{ ad.introduction }}
            </p>
            <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus !</a>
             {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">
                Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !<P>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
        </button>
    </div>
{% endblock _annonce_images_widget %}

{% block _annonce_images_entry_row %}
    {{ form_widget(form) }}
{% endblock _annonce_images_entry_row %}

{% block _annonce_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
           <div class="col-md-10">
                <div class="row">
                    <div class="col-md-6">
                        {{ form_widget(form.url) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
           </div>
           <div class="col-md-2">
                <button type="button" class="btn btn-danger" data-action="delete" 
                data-target="#block_{{id}}">X</button>
           </div>
        </div>
    </div>
{% endblock _annonce_images_entry_widget %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edition d'une annonce{% endblock title %}

{% form_theme form "ad/_collection.html.twig" %}

{% block body %}

    <div class="container">
        <h4 class="my-3">Modifier l'annonce : <em>{{ad.title}}</em></h4>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <div class="text-center">
            <button type="submit" class="btn btn-success">
                <i class="fas fa-check"></i>
                Enregistrer les modifications
            </button>
        </div>

        {{ form_end(form) }}

    </div>

{% endblock body %}

{% block javascripts %}
    {{ encore_entry_script_tags('ad') }}
{% endblock javascripts %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces !{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4">Voici les annonces de nos hôtes !</h1>

        <div class="row">
            {% for ad in ads %}
               {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock title %}

{% form_theme form "ad/_collection.html.twig" %}

{% block body %}
    <div class="container">
        <h1 class="my-3">Créer une nouvelle annonce</h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <div class="text-center">
            <button type="submit" class="btn btn-success ">
                <i class="fas fa-check"></i>
                Créer la nouvelle annonce
            </button>
        </div>

        {{ form_end(form) }}

    </div>

{% endblock body %}

{% block javascripts %}
    {{ encore_entry_script_tags('ad') }}}
{% endblock javascripts %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ ad.title }}
{% endblock title %}

{% block body %}
    <div class="ad-title" style="background-image : url({{ ad.coverImage }})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price|number_format(2, ',', ' ') }} &euro;</strong> 
                la nuit
            </p>
            <a href="{{path('create_booking', {'slug': ad.slug})}}" class="btn btn-primary mt-3">Réserver !</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">
                Modifier l'annonce</a>
                
                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger" 
                onclick="return confirm(`Êtes vous sûr de vouloir supprimer l'annonce : {{ad.title}} ?`)">
                Supprimer l'annonce</a>
            {% endif %}

        </div>
    
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content|raw }}

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" 
                            {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img class="d-block w-100" src="{{ image.url }}" alt="First slide">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <hr>

                {% if ad.comments|length > 0 %}
                    <h2 class="mb-3">Commentaires de nos voyageurs</h2>

                    <div class="alert alert-info">
                        <h4 class="alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    Note globale donnée par nos voyageurs
                                </div>
                                <div class="col-md-6">
                                    {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %} <br>
                                    <small>(Calculée sur {{ad.comments|length}} avis !)</small>
                                </div>
                            </div>
                        </h4>
                    </div>

                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 py-3 px-3">
                            <strong>{{comment.author.fullName}}</strong>, le {{comment.createdAt|date('m/d/Y')}} :
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>Note donnée</strong> :
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h6>Cette annonce n'a pas encore reçue de commentaire.</h6>
                {% endif %}
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-3">
                        <a href="{{ path('user_show', {'pseudo': user.pseudo}) }}">
                            <img src="{{ad.author.picture}}" class="avatar avatar-medium" alt="Avatar de {{ad.author.fullName}}">
                        </a>
                    </div>
                    <div class="col-md-9">
                        <a href="{{ path('user_show', {'pseudo': user.pseudo}) }}">
                            <h4>{{ad.author.fullName}}</h4>
                        </a>
                        <span class="badge badge-primary">{{ad.author.ads|length}} annonces</span>
                    </div>
                </div>
                {{ad.author.description|raw}}
            </div>
    
        </div>
    
    </div>

{% endblock body %}